# fly.toml app configuration file generated for meupetideal-backend on 2023-10-29T23:11:07-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meupetideal-backend"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
